travis:
  secure:
    BINSTAR_TOKEN: 2yT2HY1tuTe89N0PEINDUo+nJ+TTavLquR+kmr3CNvxNYPIAEAonvVZLvu7doOuWIm+gmfiMJwgHkoOqblYNoyTEUuCvK8Bg+sG2tyrFY9Padf5nPi4E7pqX3MDPYTLvqfE1B/lHG+JALvKMgCrBjNzKkx9y+qCih1LIwYOk6yBFA7obxkTDJUYHJZjDLOVYV9CWFHEPK6zYtp8uWJ9IPVomiGQOIu2nWaxwoX58dvBcPwNOiMkDqpL6A5l8nD3xvyJNJ8oHl9kqhBiQZnEn2onS6q/0ZvJy5zwILhXn0k33VxN+kFQF0Dvev8345W+SQ1PrWSdPC0MhIInwTRM8eeKWU6ApAeTEQA+rkLc2QRKDwmit5VeGpXdbN1FcffK97Y5czBrxKxSB1TAQQoB16dMdK0ItdfFvZURpdL2ezKnhe7psZjh7YCioc5aVFHLHtm8JbaDEizV6q8v3Ox8DK1cVYvK6sSrriBBnejMKBwSKEsBvp7EnXbuHt/j2GuwS/ZPp0RJYjAgSuZseUGwifCORkXYiKRMc6h7Nc8r/2Gp30/2JO3AQzSmWcoIWZsehqCgmixrKVUlrNRA4+nTXr7EFvr3vpL7gxpmbQsB6BPg7/SOwNVE/Rkigb5p1ZSYKQEYxHclyUEw6ptFtTvh6X4+pDhzwoj9htTAl01WXqdU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
