travis:
  secure:
    BINSTAR_TOKEN: bkq/T8ACuNlCK8YhD6kUb3t03RcQ9tGUkIFWwX/0kvam9Cr6rCsbHobuAJsV+EYqiudfdMe5SgzsWaNVQdFdafbSkYT/XUWeQ4uJMToM+nkTuHLrqgDI4X3zxAG9vfBOUKIc9f2FjwPZhs4ET4xxq1R2XXs/uZ74b4Nis2lA88H86ptiRfYL4E9UBqbawy1sGSwOhunmUF+GWuKaQp6CGXAp7N3x1N9K14rQXd+3gXNtDbNOmdUl536+R+oNznAqCO4bOjyJmlOICpL6xUL0XsPhiCDkAFuQ0ocwYlQIYmqPmXZ0ZIiWzdobJpnt9Ml8eEaPd32yrUcuwukHj9Pc+iHyQrsAhg3DI14CmOb/JihcrmECoc/3bTaisK/cg/K6T7ca/u5yfNTgRAbqeiil5Bk6TrtOgYpbwqy/pQoVZFOhQ4j5e9Ij3K69PXuzPO5ra56lm54WrEOsg7082HLeD7ReHKqsEabHGBUBcAkXaZA982d7/W+6E+FD5hGhkjWK9L6YUqRocB+4OmwGvZr/S5yRxwBYVk4dROsoAv3LdJ1a6LDq3djt5dd6a6D51MneKQuMDLe/6wSnMLIPAfuT44MKKclojX/JjOwpup0ZbCJeBCEs2oEL2FJD+DpxWnWghJ9ScWivU2o2QZx3YTs+HulY6Z9E4ujIYqARugioBbU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
