travis:
  secure:
    BINSTAR_TOKEN: RHkJw++35lQMe4Vt1u54mgdnORlOdH+sFDwZGEnjNj+jCSWSZSUHBWjnk49in6V2Qi/odNgnscIBJHtli6juEHa7AehUrAX7GplOG204mMgAaWNMTkdInRfL4sFL5g75VlJF7grj6jE/4ZQW4eAISWrsOvgvqQb84Dl6G96T/5nNnDmgxFQx4M+grkr9OaLto25edbPcetFlUrNYG4C40W4uYT9w4bUoqLpa8kgRtjR+fsgwnZjMQsDdhVX5Y4qjo9Myn5puX2sfo66Jp6j+W499uBwvZ08d1Z9USsrXD+QIIOg0T8X2+f7ysa9YUeDXrE8QQ3aofFN//AtFgFmr+wvnNG+a33MnTwXPNA3KMuMqkfDjjaveTNCY8eKAtvFUmoA2ToY8K+n/S+YFujpZc2uR7bKs8XVPiHgqpRYimBoOBCKxxO6dyTiPOW4LqkyuDLTZM+fv2r1LOEZCHV0r00pWrmIOUd93JRgcOkAyySOhwCB/GPbN6PA+29bXKtcL+UvjPJytH4HeP7dyqiG7pAYV+IdwdPJUUxWoeIwnzE6BPsnx63L1QpWOLnXsnfaqFD2uA8ezkP7qK2l748AcOuxIh8VHt+UkATm/Ib18hljpmgCV2UPRiXG98GpoJZSKT1AHi7idK/imkKYUX4HeDNX5R1IbXVa0ed45/qZpIyg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
